name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: "./gradlew build -PexcludeTests='**/TestSuiteTest.class'"
    - name: Create test reports
      run: ./gradlew jacocoTestReport
    - name: Upload code coverage report
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bash <(curl -s https://codecov.io/bash)

  runTestSuite:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run test suite
      env:
        GRADLE_OPTS: "-Xmx2048m"
      run: "./gradlew :citeproc-java:test --tests=TestSuiteTest --no-daemon"

  publishDockerImage:
    needs: [build, runTestSuite]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run: echo $DOCKER_HUB_ACCESS_TOKEN | docker login --username michelkraemer --password-stdin
      env:
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build Docker image
      run: docker build -t michelkraemer/citeproc-java:latest .
    - name: Push to Docker Hub
      run: docker push michelkraemer/citeproc-java:latest
